hotel/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .import views
from .views import  HotelSearchView1,show_review, hotel_detail1, hotel_list,hotel_detail,RoomListView, BookingList, RoomDetailView,RoomDetailView1, review_success, review, HotelSearchView, HotelSelectionView
app_name='hotel'

urlpatterns=[
    path('room_list/',RoomListView, name='RoomList'), #view er Roomlist ke room_list hishebe view korbe
    path('room_list1/',views.RoomListView1, name='RoomList1'),
    path('booking_list/',BookingList.as_view(), name='BookingList'), # view er BookingList ke booking_list hishebe url nibe 
    path('room/<str:selected_room_type>/', views.room_detail_view, name='room_detail'),
    path('room/<str:selected_room_type>/', views.room_detail_view1, name='room_detail1'),
    path('room/<category>', RoomDetailView.as_view(), name='RoomDetailView'),
    path('room/<category>', RoomDetailView1.as_view(), name='RoomDetailView1'),
    path('review/', review, name='review'),
    path('review_success/', review_success, name='review_success'),
    path('hotel_search_results/', HotelSearchView.as_view(), name='hotel_search'),
    path('hotel-selection/', HotelSelectionView.as_view(), name='hotel_selection'),
    path('hotel_list/', hotel_list, name='hotel_list'),
    path('hotel_detail/<id>/', hotel_detail, name='hotel_detail'),
    path('hotel_search_results1/', HotelSearchView1.as_view(), name='hotel_search1'),
    path('hotel_detail1/<id>/', hotel_detail1, name='hotel_detail1'),
    path('show_review/', show_review, name='show_review'),
    path('auth/',include('auth_app.urls'))
    

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#url--views

hotel_management/urls.py
from django.contrib import admin
from django.urls import include,path
from hotel_management import views
from django.conf import settings
from django.conf.urls.static import static
from .views import help_page, chat_with_ai,send_query_to_employee,homepage, news_details, best_hotel, world_tourist_spot, event_management,customer_service, terms_conditions, facilities, contact, aboutus, customer_view, customer_register
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('hotel.urls')),
    path('', homepage, name='HomePage'),
    path('help_page/', help_page, name='help_page'),
    path('chat/', chat_with_ai, name='chat_with_ai'),
    path('send_query/', send_query_to_employee, name='send_query_to_employee'),
    path('news&details/',news_details,name='News&Details'),
    path('besthotel/', best_hotel, name='BestHotel'),
    path('worldtouristspot/', world_tourist_spot, name='WorldTouristSpot'),
    path('eventmanagement/', event_management, name='EventManagement'),
    path('customerservice/', customer_service, name='CustomerService'),
    path('terms&conditions/', terms_conditions, name='Terms&Conditions'),
    path('facilities/', facilities, name='Facilities'),
    path('contact/', contact, name='Contact'),
    path('aboutus/', aboutus, name='AboutUs'),
    path('customerview/', customer_view, name='Customer'),
    path('customerregister/', customer_register, name='Customer'),
    path('auth/',include('auth_app.urls')),
    path("",include("paymenthandle.urls"))
   
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hotel/models.py
from django.db import models
from django.conf import settings #user model from settings
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _


# Create your models here.
class Hotel(models.Model):
    id= models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField()
   
    
    def __str__(self):
        return self.name
    

    
    
class Room(models.Model):
    
    Room_Categories=(
        ('YAC', 'AC'),
        ('NAC', 'NON-AC'),
        ('DEL', 'DELUXE'),
        ('KIN', 'KING'),
        ('QUE', 'QUEEN'),
    ) #left for database,Right to show
    
    number=models.IntegerField()
    category=models.CharField(max_length=3, choices=Room_Categories)
    beds=models.IntegerField()
    capacity=models.IntegerField()

    def __str__(self): #whenever you do something with your model it will show you this representation
        return f'{self.number}.{self.category} with {self.beds} beds for {self.capacity} people '


class Booking(models.Model):
    
    user=models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) #settings have authUsermodel,
    room=models.ForeignKey(Room, on_delete=models.CASCADE)
    check_in=models.DateTimeField()
    check_out=models.DateTimeField()
    
    def __str__(self):
        return f'{self.user} has booked {self.room} from {self.check_in} to {self.check_out}'

class Review(models.Model):
    rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Rating: {self.rating}"

class PromoCode(models.Model):
    code = models.CharField(max_length=50, unique=True)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    

hotel/forms.py
from django import forms
from .models import Review

#if  room is available book straight away,otherwise redirect to other section


class AvailabilityForm(forms.Form):
    
    check_in=forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M" ,])
    check_out=forms.DateTimeField(required=True, input_formats=["%Y-%m-%dT%H:%M" ,])
    
class ReviewForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea)
    rating = forms.IntegerField(min_value=1, max_value=5)

hotel/views.py
from django.shortcuts import render ,get_object_or_404,redirect
from django.http import HttpResponse, HttpResponseRedirect

from django.views.generic import ListView, FormView , View, DetailView
from django.urls import reverse

from .models import  Room,Booking, Review, Hotel, PromoCode
from .forms import  AvailabilityForm, ReviewForm

from hotel.booking_functions.availability import check_availability

# Create your views here.
from .models import PromoCode

def homepage(request):
    promo_codes = PromoCode.objects.all()  # Assuming you have a PromoCode model
    return render(request, 'index.html', {'promo_codes': promo_codes})

class HotelSelectionView(View):
    def get(self, request, hotel_id):
        try:
            hotel = Hotel.objects.get(id=hotel_id)
            return redirect('room_list', hotel_id=hotel.id)
        except Hotel.DoesNotExist:
            return render(request, 'hotel_not_found.html')
        
class HotelSearchView(View):
    def get(self, request):
        query = request.GET.get('query', '')
        hotels = Hotel.objects.filter(location__icontains=query) | Hotel.objects.filter(name__icontains=query)
        return render(request, 'hotel_search_results.html', {'hotels': hotels, 'query': query})
    
class HotelSearchView1(View):
    def get(self, request):
        query = request.GET.get('query', '')
        hotels = Hotel.objects.filter(location__icontains=query) | Hotel.objects.filter(name__icontains=query)
        return render(request, 'hotel_search_results1.html', {'hotels': hotels, 'query': query})

def hotel_list(request):
    hotels = Hotel.objects.all()
    return render(request, 'hotel_list.html', {'hotels': hotels})

def hotel_detail(request, id):
    hotel = get_object_or_404(Hotel, id=id)
    rooms = Room.objects.filter(id=id)
  
    return render(request, 'hotel_detail.html', {'hotel': hotel, 'rooms':rooms})

def hotel_detail1(request, id):
    hotel = get_object_or_404(Hotel, id=id)
    rooms = Room.objects.filter(id=id)
  
    return render(request, 'hotel_detail1.html', {'hotel': hotel, 'rooms':rooms})

def RoomListView(request) : 
    room=Room.objects.all()[0]
    room_categories= dict(room.Room_Categories)
    
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView' , kwargs={'category':room_category})
        
        # print(room,room_url)
        room_list.append((room,room_url))
        
        
        
    
    context={
        "room_list":room_list,
    }
    print(room_list)
    return render(request, 'room_list_view.html',context)

def RoomListView(request) : 
    room=Room.objects.all()[0]
    room_categories= dict(room.Room_Categories)
    
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView' , kwargs={'category':room_category})
        
        # print(room,room_url)
        room_list.append((room,room_url))
        
        
        
    
    context={
        "room_list":room_list,
    }
    print(room_list)
    return render(request, 'room_list_view.html',context)

def RoomListView1(request) : 
    room=Room.objects.all()[0]
    room_categories= dict(room.Room_Categories)
    
    room_values=room_categories.values()
    room_list=[]
    for room_category in room_categories:
        room=room_categories.get(room_category)
        room_url=reverse('hotel:RoomDetailView1' , kwargs={'category':room_category})
        
        # print(room,room_url)
        room_list.append((room,room_url))
        
        
        
    
    context={
        "room_list":room_list,
    }
    print(room_list)
    return render(request, 'room_list_view1.html',context)




class BookingList(ListView) :
    model=Booking


class RoomDetailView(View):
    def get(self, request, *args , **kwargs):
        category=self.kwargs.get('category', None)
        form=AvailabilityForm()

        room_list=Room.objects.filter(category=category) 

        if len(room_list)>0:
            room=room_list[0]
            room_category= dict(room.Room_Categories).get(room.category,None)
            context={
            'room_category': room_category,
            'form': form,
            'selected_room_type': category ,
            }
            return render(request, 'room_detail_view.html', context)

        else:
            return HttpResponse('Category Does Not Exist')


    def post(self, request, *args , **kwargs):
        category=self.kwargs.get('category', None)
        room_list=Room.objects.filter(category=category) 
        form=AvailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data

        available_rooms=[]
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)


        if len(available_rooms)>0:
         room=available_rooms[0]
         booking=Booking.objects.create(
            user=self.request.user,
            room =room,
            check_in=data['check_in'],
            check_out=data['check_out']

         )

         booking.save() 
         return HttpResponse(booking)
        else :
            return HttpResponse('All of This category of rooms are booked !! Try Another One..Good Luck !!')


class RoomDetailView1(View):
    def get(self, request, *args , **kwargs):
        category=self.kwargs.get('category', None)
        form=AvailabilityForm()

        room_list=Room.objects.filter(category=category) 

        if len(room_list)>0:
            room=room_list[0]
            room_category= dict(room.Room_Categories).get(room.category,None)
            context={
            'room_category': room_category,
            'form': form,
            'selected_room_type': category ,
            }
            return render(request, 'room_detail_view1.html', context)

        else:
            return HttpResponse('Category Does Not Exist')


    def post(self, request, *args , **kwargs):
        category=self.kwargs.get('category', None)
        room_list=Room.objects.filter(category=category) 
        form=AvailabilityForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data

        available_rooms=[]
        for room in room_list:
            if check_availability(room, data['check_in'], data['check_out']):
                available_rooms.append(room)


        if len(available_rooms)>0:
         room=available_rooms[0]
         booking=Booking.objects.create(
            user=self.request.user,
            room =room,
            check_in=data['check_in'],
            check_out=data['check_out']

         )

         booking.save() 
         return HttpResponse(booking)
        else :
            return HttpResponse('All of This category of rooms are booked !! Try Another One..Good Luck !!')

       
        
def review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = Review.objects.create(
            rating=form.cleaned_data['rating'],
            comment=form.cleaned_data['comment']
            )
            
            return redirect('hotel:review_success')
    else:
        form = ReviewForm()
    return render(request, 'review.html', {'form': form})

def review_success(request):
    return render(request, 'review_success.html')



def show_review(request):
    reviews = Review.objects.all()
    return render(request, 'show_review.html', {'reviews': reviews})

def room_detail_view(request, selected_room_type):
    # Your code to handle room booking
    # Assuming selected_room_type is determined dynamically
    
    # Pass the selected room type to the payment form view
    room_options = [
        {'value': 'NAC', 'label': 'Non AC'},
        {'value': 'YAC', 'label': 'AC'},
        {'value': 'DEL', 'label': 'Deluxe'},
        {'value': 'KIN', 'label': 'King'},
        {'value': 'QUE', 'label': 'Queen'},
    ]
    return render(request, 'payment_form.html', {'selected_room_type': selected_room_type, 'room_options': room_options})

def room_detail_view1(request, selected_room_type):
    # Your code to handle room booking
    # Assuming selected_room_type is determined dynamically
    
    # Pass the selected room type to the payment form view
    room_options = [
        {'value': 'NAC', 'label': 'Non AC'},
        {'value': 'YAC', 'label': 'AC'},
        {'value': 'DEL', 'label': 'Deluxe'},
        {'value': 'KIN', 'label': 'King'},
        {'value': 'QUE', 'label': 'Queen'},
    ]
    return render(request, 'room_detail_view1.html', {'selected_room_type': selected_room_type, 'room_options': room_options})

hotel/templates/availability_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book a Room</title>

    <!-- Include jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- JavaScript code for date picker -->
    <script>
        $(document).ready(function() {
            // Get today's date
            var today = new Date();

            // Initialize date picker for check-in field
            $('#id_check_in').datepicker({
                minDate: today,
                dateFormat: 'yy-mm-dd'
            });

            // Initialize date picker for check-out field
            $('#id_check_out').datepicker({
                minDate: today,
                dateFormat: 'yy-mm-dd'
            });
        });
    </script>
</head>
<body>
    <form action="" method="POST">
        <!-- post method sends data to the server -->
        {{ form.as_p }} 
        <!-- submission originates from the same site and user session -->
        {% csrf_token %}
        <button type="submit">Book Room</button>
    </form>
</body>
</html>

hotel/templates/hotel_detail.html
<!-- hotel_detail.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ hotel.name }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/hotel_detail.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<style>
    /* Additional CSS for hotel_detail.css */
.hotel-detail1-body {
    background-image: url('{% static "pics/c45ccc6f1c46da901454ab5fcd076884.jpg"  %}');
    background-size: cover; /* Cover the entire background */
    background-repeat: no-repeat; /* Do not repeat the background image */
    background-position: center center; /* Center the background image */
    height: 100vh;
    display: flex; /* Center content vertically */
    justify-content: center; /* Center content horizontally */
    align-items: center; /* Center content vertically */
}

.content-container {
    background-color: rgba(0, 0, 0, 0.5); /* Transparent black background */
    padding: 20px; /* Add padding to create space around content */
    border-radius: 10px; /* Add border radius for rounded corners */
    text-align: center; /* Center text */
    max-width: 80%; /* Limit width of content */
}

h1 {
    color: white; /* Set text color to white */
    font-size: 36px; /* Increase font size */
    margin-bottom: 20px; /* Add space below text */
}

.description {
    color: white; /* Set text color to white */
    font-size: 20px; /* Increase font size */
    margin-bottom: 20px; /* Add space below text */
}

.book-btn-container {
    margin-top: 20px; /* Add space above the button */
}

.book-btn {
    display: inline-block;
    padding: 15px 30px; /* Increase padding */
    background-color: white; /* Set button background color to white */
    color: black; /* Set button text color to black */
    text-decoration: none;
    border-radius: 8px; /* Increase border radius */
    transition: background-color 0.3s ease;
    font-size: 20px; /* Increase font size */
}

.book-btn:hover {
    background-color: #ddd; /* Darken button background color on hover */
}
.rooms-available  {
    margin-top: 0; 
    color: white;/* Remove top margin of h2 */
}
.back-btn-container {
    position: absolute;
    top: 20px; /* Adjust vertical position */
    right: 20px; /* Adjust horizontal position */
}

/* Back button */
.back-btn {
    padding: 10px 15px; /* Adjust padding */
    background-color: #333; /* Button background color */
    color: white; /* Button text color */
    text-decoration: none;
    border-radius: 5px; /* Button border radius */
    font-size: 16px; /* Button font size */
    transition: background-color 0.3s ease;
}

.back-btn:hover {
    background-color: #555; /* Darken button background color on hover */
}

</style>
<body class="hotel-detail1-body">
    <div class="content-container">
        <h1>{{ hotel.name }}</h1>
        <p class="description">{{ hotel.description }}</p>
        <!-- Room list -->
        <div class="rooms-available h2">
            <h2>Rooms Available:</h2>
            </div>
            <div class="book-btn-container">
                <a href="/room_list/" class="book-btn">Rooms</a>
            </div>
        <!-- Centered book button -->
        <div class="book-btn-container">
            <a href="{% url 'process_payment' %}?id={{ hotel.id }}&room_type={{ room_category }}" class="book-btn">Book</a>
        </div>
        <div class="back-btn-container">
            <a href="#" onclick="goBack()" class="back-btn"><i class="fas fa-arrow-left"></i> Back</a>
        </div>
        <!-- Hotel images -->
        <div class="hotel-images-container">
            {% for image in hotel.images.all %}
            <img src="{% static 'pics/' %}{{ image }}" alt="Hotel Image" class="hotel-image">
            {% endfor %}
        </div>
    </div>
    <script>
        function goBack() {
            var previousPage = getPreviousPage();
            if (previousPage === 'hotel_search_result') {
                history.back();
            } else {
                window.location.href = "/hotel_list/";
            }
        }
    
        function getPreviousPage() {
            // Get the referrer URL
            var referrer = document.referrer;
            // Check if the referrer URL contains 'hotel_search_result'
            if (referrer.includes('hotel_search_result')) {
                return 'hotel_search_result';
            } else {
                return 'other';
            }
        }
    </script>
</body>
</html>

hotel/templates/hotel_detail1.html
<!-- hotel_detail.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ hotel.name }}</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/hotel_detail.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<style>
    /* Additional CSS for hotel_detail.css */
.hotel-detail1-body {
    background-image: url('{% static "pics/c45ccc6f1c46da901454ab5fcd076884.jpg"  %}');
    background-size: cover; /* Cover the entire background */
    background-repeat: no-repeat; /* Do not repeat the background image */
    background-position: center center; /* Center the background image */
    height: 100vh;
    display: flex; /* Center content vertically */
    justify-content: center; /* Center content horizontally */
    align-items: center; /* Center content vertically */
}

.content-container {
    background-color: rgba(0, 0, 0, 0.5); /* Transparent black background */
    padding: 20px; /* Add padding to create space around content */
    border-radius: 10px; /* Add border radius for rounded corners */
    text-align: center; /* Center text */
    max-width: 80%; /* Limit width of content */
}

h1 {
    color: white; /* Set text color to white */
    font-size: 36px; /* Increase font size */
    margin-bottom: 20px; /* Add space below text */
}

.description {
    color: white; /* Set text color to white */
    font-size: 20px; /* Increase font size */
    margin-bottom: 20px; /* Add space below text */
}

.book-btn-container {
    margin-top: 20px; /* Add space above the button */
}

.book-btn {
    display: inline-block;
    padding: 15px 30px; /* Increase padding */
    background-color: white; /* Set button background color to white */
    color: black; /* Set button text color to black */
    text-decoration: none;
    border-radius: 8px; /* Increase border radius */
    transition: background-color 0.3s ease;
    font-size: 20px; /* Increase font size */
}

.book-btn:hover {
    background-color: #ddd; /* Darken button background color on hover */
}


.rooms-available  {
    margin-top: 0; 
    color: white;/* Remove top margin of h2 */
}
.back-btn-container {
    position: absolute;
    top: 20px; /* Adjust vertical position */
    right: 20px; /* Adjust horizontal position */
}

/* Back button */
.back-btn {
    padding: 10px 15px; /* Adjust padding */
    background-color: #333; /* Button background color */
    color: white; /* Button text color */
    text-decoration: none;
    border-radius: 5px; /* Button border radius */
    font-size: 16px; /* Button font size */
    transition: background-color 0.3s ease;
}

.back-btn:hover {
    background-color: #555; /* Darken button background color on hover */
}


</style>
<body class="hotel-detail1-body">
    <div class="content-container">
        <h1>{{ hotel.name }}</h1>
        <p class="description">{{ hotel.description }}</p>
        <!-- Room list -->
        <div class="rooms-available h2">
        <h2>Rooms Available:</h2>
        </div>
        <div class="book-btn-container">
            <a href="/room_list1/" class="book-btn">Rooms</a>
        </div>
   
   
        
        <!-- Centered book button -->
        <div class="book-btn-container">
            <a href="/auth/login/" class="book-btn">Book</a>
        </div>
        <div class="back-btn-container">
            <a href="/hotel_search_results1/"  class="back-btn"><i class="fas fa-arrow-left"></i> Back</a>
        </div>
        <!-- Hotel images -->
        <div class="hotel-images-container">
            {% for image in hotel.images.all %}
            <img src="{% static 'pics/' %}{{ image }}" alt="Hotel Image" class="hotel-image">
            {% endfor %}
        </div>
    </div>
</body>
</html>

hotel/templates/hotel_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel List</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        /* CSS styles for hotel list */
        .hotel-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            padding: 20px;
        }
        
        .hotel-card {
            width: 300px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        .hotel-card img {
            width: 100%;
            height: 200px;
            object-fit: cover;
        }
        
        .hotel-info {
            padding: 15px;
        }
        
        .hotel-info h2 {
            margin-top: 0;
            margin-bottom: 10px;
        }
        
        .hotel-info p {
            margin: 0;
        }
        
        .hotel-info a {
            display: block;
            text-align: center;
            margin-top: 10px;
            text-decoration: none;
            color: #333;
            background-color: #f0f0f0;
            padding: 8px 0;
            border-radius: 3px;
            transition: background-color 0.3s ease;
        }
        
        .hotel-info a:hover {
            background-color: #ddd;
        }

        .home a {
            display: inline-block;
            padding: 15px 0;
            color: black;
            text-decoration: none;
            font-weight: bold;
            border-right: 1px solid #ccc;
            margin-right: 10px;
        }

        .home a:last-child {
            border-right: none;
            margin-right: 0;
        }

        .home a i {
            margin-right: 5px;
        }
        
    </style>
</head>
<body>
    <div class="home">
        <a href="/auth/dashboard/"><i class="fas fa-arrow-alt-circle-left"></i>Home </a>
    </div>
    <h1>Hotel List</h1>
    <div class="hotel-list">
        {% for hotel in hotels %}
        <div class="hotel-card">
            <!-- Use the hotel's image if available, otherwise use a placeholder -->
            <img src="{% static 'pics/' %}{{ hotel.name }}.jpg" alt="{{ hotel.name }}">
            <div class="hotel-info">
                <h2>{{ hotel.name }}</h2>
                <p>{{ hotel.location }}</p>
                <p>{{ hotel.brief_summary }}</p>
                <!-- Use the url template tag to generate the URL for room list -->
                <a href="/hotel_detail/{{ hotel.id }}/">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>

hotel/templates/hotel_not_found.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hotel Not Found</title>
</head>
<body>
    <h1>Hotel Not Found</h1>
    <p>The hotel you are looking for does not exist.</p>
</body>
</html>

hotel/templates/hotel_search_results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search Results</title>
    {% load static %}
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

    <style>
        /* Additional CSS for search results */
        /* Ensure that the styles from hotel_list.html are applied here as well */
        .hotel-list {
            display: flex;
            flex-wrap: wrap;
            justify-content: space-around;
            padding: 20px;
        }
        
        .hotel-card {
            width: 300px;
            border: 1px solid #ccc;
            border-radius: 5px;
            margin-bottom: 20px;
            overflow: hidden;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        
        .hotel-card img {
            width: 100%;
            height: 200px;
            object-fit: cover;
        }
        
        .hotel-info {
            padding: 15px;
        }
        
        .hotel-info h2 {
            margin-top: 0;
            margin-bottom: 10px;
        }
        
        .hotel-info p {
            margin: 0;
        }
        
        .hotel-info a {
            display: block;
            text-align: center;
            margin-top: 10px;
            text-decoration: none;
            color: #333;
            background-color: #f0f0f0;
            padding: 8px 0;
            border-radius: 3px;
            transition: background-color 0.3s ease;
        }
        
        .hotel-info a:hover {
            background-color: #ddd;
        }
        .home a {
            display: inline-block;
            padding: 15px 0;
            color: black;
            text-decoration: none;
            font-weight: bold;
            border-right: 1px solid #ccc;
            margin-right: 10px;
        }

        .home a:last-child {
            border-right: none;
            margin-right: 0;
        }

        .home a i {
            margin-right: 5px;
        }
    </style>
</head>
<body>
    <div class="home">
        <a href="/"><i class="fas fa-arrow-alt-circle-left"></i>Home </a>
    </div>
    {% if hotels %}
    <h1>Search Results for "{{ query }}"</h1>
    <div class="hotel-list">
        {% for hotel in hotels %}
        <div class="hotel-card">
            <!-- Use the hotel's image if available, otherwise use a placeholder -->
            <img src="{% static 'pics/' %}{{ hotel.name }}.jpg" alt="{{ hotel.name }}">
            <div class="hotel-info">
                <h2>{{ hotel.name }}</h2>
                <p>{{ hotel.location }}</p>
                <p>{{ hotel.brief_summary }}</p>
                <!-- Use the url template tag to generate the URL for hotel detail -->
                <a href="/hotel_detail/{{ hotel.id }}/">View</a>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>No hotels found for "{{ query }}".</p>
    {% endif %}
</body>
</html>